#!/usr/bin/env python
"""Remaining paper tables (analogues of the original's T6, T13-T16), generated
from committed artifacts into outputs/study_b/r6/results/PAPER_TABLES.md
(the released copy is artifacts/r6/PAPER_TABLES.md).

  .venv/bin/python -m study_b.r6_paper_tables
"""
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

OUT = Path("outputs/study_b/r6/results")
DIM_NAMES = {"PUR": "Purpose", "AUD": "Audience", "STR": "Structure and flow",
             "EXP": "Explanation", "EVD": "Evidence", "VOC": "Voices",
             "ACT": "Actionability", "COM": "Commercial integration",
             "TIM": "Timeliness", "PAG": "Page format", "WRI": "Writing style",
             "STY": "Writing style"}


def features_index():
    tax = json.loads(Path("outputs/study_b/r3/dedup/condensed_taxonomy_0.85.json").read_text())
    idx = {}
    def walk(x):
        if isinstance(x, dict):
            if "id" in x and "name" in x:
                idx[x["id"]] = x
            for v in x.values():
                walk(v)
        elif isinstance(x, list):
            for v in x:
                walk(v)
    walk(tax)
    return idx


def value_label(col, idx):
    fid, _, val = col.partition("__")
    f = idx.get(fid, {})
    name = f.get("name", fid)
    if val == "ord":
        return fid, name, "(ordinal position)"
    return fid, name, "= " + val.replace("_", " ")


def main() -> int:
    idx = features_index()
    variants = json.load(open("outputs/study_b/r6/variant_sets.json"))
    instrument = sorted(set(variants["all_features"]))
    cv = json.load(open(OUT / "core_values_selection.json"))
    fp = json.load(open(OUT / "parity_fixes.json"))["p2_core_fingerprint"]["fingerprints"]

    lines = ["# Paper tables T6 + T13-T16 (analogues of the original's exhibits)",
             "", "Generated by study_b/r6_paper_tables.py from committed "
             "artifacts; regenerate rather than hand-edit.", ""]

    # ---- T6: feature distribution by dimension and type --------------------
    lines += ["## T6 - Frozen-instrument composition (214 features)",
              "", "| Dimension | Features | Types (categorical/binary/ordinal/scale/multi) | Example feature |",
              "|---|---|---|---|"]
    by_dim = {}
    for fid in instrument:
        by_dim.setdefault(fid[:3], []).append(fid)
    for pre, fids in sorted(by_dim.items(), key=lambda kv: -len(kv[1])):
        types = Counter(idx.get(f, {}).get("type", "?") for f in fids)
        tstr = "/".join(str(types.get(t, 0)) for t in
                        ("categorical", "binary", "ordinal", "scale",
                         "multi_select"))
        ex = idx.get(fids[0], {})
        lines.append(f"| {DIM_NAMES.get(pre, pre)} | {len(fids)} | {tstr} | "
                     f"{ex.get('name', fids[0])} |")
    lines.append("")

    # ---- T13/T14: AI- and human-characterizing core values -----------------
    signs, gaps = cv["value_signs"], cv["value_gaps"]
    for tid, side, orig_n in (("T13", "ai", "theirs: 20"),
                              ("T14", "human", "theirs: 13")):
        vals = sorted((c for c in signs if signs[c] == side),
                      key=lambda c: -gaps[c])
        lines += [f"## {tid} - {side.upper()}-characterizing core values "
                  f"({len(vals)}; {orig_n})", "",
                  "| Feature | Value | Human-AI gap |", "|---|---|---|"]
        for c in vals:
            fid, name, vlab = value_label(c, idx)
            lines.append(f"| {name} ({fid}) | {vlab} | {gaps[c]:.3f} |")
        lines.append("")

    # ---- T15: all core values with gaps ------------------------------------
    lines += ["## T15 - All core values (10) with signed direction and gap",
              "", "| Feature | Value | Leans | Gap |", "|---|---|---|---|"]
    for c in sorted(signs, key=lambda c: -gaps[c]):
        fid, name, vlab = value_label(c, idx)
        lines.append(f"| {name} ({fid}) | {vlab} | {signs[c]} | {gaps[c]:.3f} |")
    lines.append("")

    # ---- T16: per-source fingerprints --------------------------------------
    counts = {s: len(v) for s, v in fp.items()}
    lines += [f"## T16 - Per-source structural fingerprints "
              f"(counts {counts}; theirs 32/26/11/11/7/3)", "",
              "| Source | Fingerprint features (up to 5, by 6-way SHAP concentration) |",
              "|---|---|"]
    for s in ("human", "gpt", "claude", "gemini", "deepseek", "kimi"):
        names = [f"{idx.get(f, {}).get('name', f)} ({f})" for f in fp.get(s, [])[:5]]
        lines.append(f"| {s} | {'; '.join(names) if names else '-'} |")
    lines.append("")

    out = Path("outputs/study_b/r6/results/PAPER_TABLES.md")
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(lines)} lines)", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
